MODEL:
  META_ARCHITECTURE: "IDOL"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  IDOL:
    NUM_CLASSES: 1
    MULTI_CLS_ON: True
  WEIGHTS: './weights/R-50.pkl'
#  WEIGHTS: ''
DATASETS:
  TRAIN: ("coco_2017_train_agn",)
  TEST: ("coco_2017_val_agn",)
SOLVER:
  IMS_PER_BATCH: 8
#  IMS_PER_BATCH: 1
  BASE_LR: 0.0002
  STEPS: (81625,122437)
  MAX_ITER: 163250
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 10000
INPUT:
  SAMPLING_FRAME_NUM: 2
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
  COCO_PRETRAIN: True
  PRETRAIN_SAME_CROP: False
TEST:
  EVAL_PERIOD: 60000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2
OUTPUT_DIR: ./output